# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bae5c3700e53e362ff4b9636ed290466420adc3fdf1619f18e4bedce1532bc30c350252c2e03e1d738528d1addb1d71365f77540fac6f568edb27743a89d42d

test:
  secret_key_base: 72fb795030b196148452d5ab4435de321a36f63da87d857748b2cb7ae927389e226cda0e1e4a8c4e75533f38226f69973e04331d8505fb946702b75010913e6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
